export const LOOKUP_PLACE = 'LOOKUP_PLACE';
export const SCAN_PARAGRAPH = 'SCAN_PARAGRAPH';
export const PAGE_SCAN = 'PAGE_SCAN';
export const PAGE_SCAN_SUCCESS = 'PAGE_SCAN_SUCCESS';
export const PAGE_SCAN_FAILED = 'PAGE_SCAN_FAILED';
